name: Minify HTML
on:
  push:
    branches: [main]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Minify HTML files
        uses: Justintime50/html-minifier-action@v1.0.0
        with:
          files: "*.html"
          options: "--collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --use-short-doctype"
      - name: Commit minified files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || git commit -am "Minify HTML" && git push
